### PR TITLE
added command not found error

### PR DESCRIPTION
**Pull request by Darin755**
I believe that I fixed all of the issues with the old fork.

### CODE REVIEW

**Comment by zrafa** [comment]
Almost there. Your changes are still changing files under conf/*, compile/* and system/*. The message of printf in main.c might be just "not found" (more free RAM/FLASH, still if it seems few bytes).

**Comment by Darin755** [comment]
Is this what you had in mind?

**Comment by Darin755** [comment]
I believe I fixed everything. Please let me know if I did not.

**Review by zrafa — APPROVED** [review]
Ok, it seems safe. Have you seen the shell under apps/ ? Now both codes will be out of sync. I will resync.

**Pull request merged**
